# Generated by Django 2.1.4 on 2019-01-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_port_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='_12th_percentage',
            field=models.DecimalField(decimal_places=2, default=44, max_digits=4),
        ),
    ]
