# Generated by Django 2.1.4 on 2019-01-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_port__12th_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='degree',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('BS', 'BS'), ('MTECH', 'MTECH')], default='BTECH', max_length=5),
        ),
    ]
