# Generated by Django 2.1.4 on 2019-01-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_port_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='degree_percentage',
            field=models.DecimalField(decimal_places=2, default=44, max_digits=5),
        ),
        migrations.AddField(
            model_name='port',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
