# Generated by Django 2.1.4 on 2019-01-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_auto_20190116_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='image',
            field=models.ImageField(default='pics/12.jpg', upload_to='pics/'),
        ),
    ]
