# Generated by Django 2.1.4 on 2019-01-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_auto_20190116_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
