# Generated by Django 2.1.4 on 2019-01-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_auto_20190116_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
