# Generated by Django 2.1.4 on 2019-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0010_auto_20190117_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
