# Generated by Django 2.1.4 on 2019-01-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0011_port_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='skills',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
