# Generated by Django 2.1.4 on 2019-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0012_auto_20190117_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='specified_skills',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('.NET', '.NET')], default='C', max_length=20),
        ),
    ]
