# Generated by Django 2.1.4 on 2019-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0013_port_specified_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='specified_skills',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('.NET', '.NET'), ('javascript', 'javascript')], default='C', max_length=20),
        ),
    ]
