# Generated by Django 2.1.4 on 2019-01-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_auto_20190119_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='port',
            name='tpercentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
