# Generated by Django 2.1.4 on 2019-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0016_auto_20190119_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
