# Generated by Django 2.1.4 on 2019-01-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0018_port_add_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='upload_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
