# Generated by Django 2.1.4 on 2019-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0019_port_upload_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='upload_video',
            field=models.FileField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
